"""HTML report generation with jinja2."""

from pathlib import Path

import matplotlib
matplotlib.use("Agg")  # Non-interactive backend
import matplotlib.pyplot as plt
import numpy as np

from tinyfold.viz.io.structure_writer import coords_to_pdb_string, write_pdb
from tinyfold.viz.mapping.atom_schema import AtomSchema
from tinyfold.viz.metrics.align import align_on_subset, kabsch_align
from tinyfold.viz.metrics.contacts import contact_map_CA, contact_metrics, interface_residues
from tinyfold.viz.metrics.rmsd import backbone_rmsd
from tinyfold.viz.plots.distributions import plot_contact_precision_recall, plot_metric_distribution, plot_rmsd_comparison
from tinyfold.viz.plots.matrices import plot_contact_map
from tinyfold.viz.render.py3dmol_viewer import make_dual_viewer_html, make_viewer_html

# Try to import jinja2, fall back to simple string formatting
try:
    from jinja2 import Template
    HAS_JINJA2 = True
except ImportError:
    HAS_JINJA2 = False


REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>TinyFold Report: {{ sample_id }}</title>
    <style>
        * { box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 0;
            padding: 20px;
            background: #f5f5f5;
            color: #333;
        }
        .header {
            background: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        .header h1 {
            margin: 0 0 8px 0;
            font-size: 24px;
        }
        .header .meta {
            color: #666;
            font-size: 14px;
        }
        .section {
            background: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        .section h2 {
            margin: 0 0 16px 0;
            font-size: 18px;
            color: #333;
            border-bottom: 2px solid #3B82F6;
            padding-bottom: 8px;
        }
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 16px;
        }
        .metric-card {
            background: #f9fafb;
            padding: 16px;
            border-radius: 6px;
            text-align: center;
        }
        .metric-card .value {
            font-size: 28px;
            font-weight: 600;
            color: #3B82F6;
        }
        .metric-card .label {
            font-size: 13px;
            color: #666;
            margin-top: 4px;
        }
        .plots-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 16px;
        }
        .plot-img {
            max-width: 100%;
            border-radius: 4px;
        }
        .viewer-frame {
            width: 100%;
            height: 550px;
            border: none;
            border-radius: 4px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 14px;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #e5e7eb;
        }
        th {
            background: #f9fafb;
            font-weight: 500;
        }
        tr:hover {
            background: #f9fafb;
        }
        .best-row {
            background: #ecfdf5 !important;
        }
        .download-links a {
            display: inline-block;
            margin-right: 12px;
            color: #3B82F6;
            text-decoration: none;
        }
        .download-links a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ sample_id }}</h1>
        <div class="meta">Generated by TinyFold Visualization</div>
    </div>

    <div class="section">
        <h2>3D Structure Viewer</h2>
        <iframe src="viewer.html" class="viewer-frame"></iframe>
        <div class="download-links" style="margin-top: 12px;">
            <a href="pred.pdb" download>Download Predicted PDB</a>
            <a href="ref.pdb" download>Download Reference PDB</a>
        </div>
    </div>

    <div class="section">
        <h2>RMSD Metrics</h2>
        <div class="metrics-grid">
            <div class="metric-card">
                <div class="value">{{ "%.2f"|format(rmsd.rmsd_complex) }}</div>
                <div class="label">Complex RMSD (Å)</div>
            </div>
            <div class="metric-card">
                <div class="value">{{ "%.2f"|format(rmsd.lrmsd) }}</div>
                <div class="label">LRMSD (Å)</div>
            </div>
            {% if rmsd.irmsd == rmsd.irmsd %}
            <div class="metric-card">
                <div class="value">{{ "%.2f"|format(rmsd.irmsd) }}</div>
                <div class="label">Interface RMSD (Å)</div>
            </div>
            {% endif %}
            <div class="metric-card">
                <div class="value">{{ "%.2f"|format(rmsd.rmsd_chain_a) }}</div>
                <div class="label">Chain A RMSD (Å)</div>
            </div>
            <div class="metric-card">
                <div class="value">{{ "%.2f"|format(rmsd.rmsd_chain_b) }}</div>
                <div class="label">Chain B RMSD (Å)</div>
            </div>
        </div>
        <div class="plots-grid" style="margin-top: 16px;">
            <img src="plots/rmsd_comparison.png" class="plot-img" alt="RMSD Comparison">
        </div>
    </div>

    <div class="section">
        <h2>Contact Prediction</h2>
        <div class="metrics-grid">
            <div class="metric-card">
                <div class="value">{{ "%.2f"|format(contacts.precision) }}</div>
                <div class="label">Precision</div>
            </div>
            <div class="metric-card">
                <div class="value">{{ "%.2f"|format(contacts.recall) }}</div>
                <div class="label">Recall</div>
            </div>
            <div class="metric-card">
                <div class="value">{{ "%.2f"|format(contacts.f1) }}</div>
                <div class="label">F1 Score</div>
            </div>
            <div class="metric-card">
                <div class="value">{{ contacts.n_pred }} / {{ contacts.n_ref }}</div>
                <div class="label">Pred / Ref Contacts</div>
            </div>
        </div>
        <div class="plots-grid" style="margin-top: 16px;">
            <img src="plots/contact_map.png" class="plot-img" alt="Contact Map">
            <img src="plots/contact_metrics.png" class="plot-img" alt="Contact Metrics">
        </div>
    </div>

    {% if samples %}
    <div class="section">
        <h2>Sample Ranking ({{ samples|length }} samples)</h2>
        <table>
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Sample</th>
                    <th>Complex RMSD</th>
                    <th>LRMSD</th>
                    <th>Contact F1</th>
                </tr>
            </thead>
            <tbody>
                {% for s in samples %}
                <tr class="{{ 'best-row' if loop.index == 1 else '' }}">
                    <td>{{ loop.index }}</td>
                    <td>{{ s.name }}</td>
                    <td>{{ "%.2f"|format(s.rmsd_complex) }} Å</td>
                    <td>{{ "%.2f"|format(s.lrmsd) }} Å</td>
                    <td>{{ "%.2f"|format(s.contact_f1) }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="plots-grid" style="margin-top: 16px;">
            <img src="plots/sample_rmsd_distribution.png" class="plot-img" alt="Sample RMSD Distribution">
        </div>
    </div>
    {% endif %}

</body>
</html>
"""


def make_report(
    sample_id: str,
    pred_xyz: np.ndarray,
    ref_xyz: np.ndarray,
    atom_to_res: np.ndarray,
    atom_type: np.ndarray,
    chain_id_res: np.ndarray,
    res_idx: np.ndarray,
    out_dir: str | Path,
    seq: np.ndarray | None = None,
    atom_mask: np.ndarray | None = None,
    interface_mask: np.ndarray | None = None,
    pred_samples: list[np.ndarray] | None = None,
    schema: AtomSchema | None = None,
) -> str:
    """Generate full HTML report for a prediction.

    Args:
        sample_id: Sample identifier
        pred_xyz: [N_atom, 3] predicted coordinates
        ref_xyz: [N_atom, 3] reference coordinates
        atom_to_res: [N_atom] residue index per atom
        atom_type: [N_atom] atom type index
        chain_id_res: [L] chain ID per residue
        res_idx: [L] within-chain residue index
        out_dir: Output directory
        seq: [L] amino acid indices (optional)
        atom_mask: [N_atom] valid atom mask (optional)
        interface_mask: [L] interface residue mask (optional)
        pred_samples: List of alternative predictions (optional)
        schema: AtomSchema (optional)

    Returns:
        Path to generated report.html
    """
    if schema is None:
        schema = AtomSchema()

    out_dir = Path(out_dir) / sample_id
    out_dir.mkdir(parents=True, exist_ok=True)
    plots_dir = out_dir / "plots"
    plots_dir.mkdir(exist_ok=True)

    # Default mask
    if atom_mask is None:
        atom_mask = np.ones(len(pred_xyz), dtype=bool)

    # Align predictions
    pred_aligned, _, _ = kabsch_align(pred_xyz, ref_xyz, mask=atom_mask)

    # Receptor-aligned (align on chain A)
    chain_a_mask = (chain_id_res[atom_to_res] == 0) & atom_mask
    pred_receptor_aligned = align_on_subset(pred_xyz, ref_xyz, chain_a_mask)

    # Compute RMSD metrics
    rmsd_metrics = backbone_rmsd(
        pred_aligned, ref_xyz, atom_to_res, chain_id_res,
        atom_mask=atom_mask, interface_mask=interface_mask
    )

    # Compute contact maps
    _, _, pred_contacts = contact_map_CA(pred_aligned, atom_type, atom_to_res, chain_id_res)
    _, _, ref_contacts = contact_map_CA(ref_xyz, atom_type, atom_to_res, chain_id_res)
    contact_met = contact_metrics(pred_contacts, ref_contacts)

    # Get interface residues if not provided
    if interface_mask is None:
        interface_mask = interface_residues(ref_contacts, chain_id_res)

    # Write PDB files
    write_pdb(
        out_dir / "pred.pdb", pred_aligned, atom_to_res, atom_type,
        chain_id_res, res_idx, seq, atom_mask, schema
    )
    write_pdb(
        out_dir / "ref.pdb", ref_xyz, atom_to_res, atom_type,
        chain_id_res, res_idx, seq, atom_mask, schema
    )

    # Generate viewer HTML
    pred_pdb = coords_to_pdb_string(
        pred_aligned, atom_to_res, atom_type, chain_id_res, res_idx, seq, atom_mask, schema
    )
    pred_receptor_pdb = coords_to_pdb_string(
        pred_receptor_aligned, atom_to_res, atom_type, chain_id_res, res_idx, seq, atom_mask, schema
    )
    ref_pdb = coords_to_pdb_string(
        ref_xyz, atom_to_res, atom_type, chain_id_res, res_idx, seq, atom_mask, schema
    )

    viewer_html = make_dual_viewer_html(
        pred_pdb, pred_receptor_pdb, ref_pdb,
        title=f"Structure: {sample_id}"
    )
    with open(out_dir / "viewer.html", "w") as f:
        f.write(viewer_html)

    # Generate plots
    plot_contact_map(pred_contacts, ref_contacts, plots_dir / "contact_map.png")
    plt.close()

    plot_rmsd_comparison(rmsd_metrics, plots_dir / "rmsd_comparison.png")
    plt.close()

    plot_contact_precision_recall(contact_met, plots_dir / "contact_metrics.png")
    plt.close()

    # Process multiple samples if provided
    samples_data = None
    if pred_samples is not None and len(pred_samples) > 1:
        samples_data = []
        sample_rmsds = []

        for i, sample_xyz in enumerate(pred_samples):
            sample_aligned, _, _ = kabsch_align(sample_xyz, ref_xyz, mask=atom_mask)
            s_rmsd = backbone_rmsd(
                sample_aligned, ref_xyz, atom_to_res, chain_id_res, atom_mask
            )
            _, _, s_contacts = contact_map_CA(sample_aligned, atom_type, atom_to_res, chain_id_res)
            s_contact_met = contact_metrics(s_contacts, ref_contacts)

            samples_data.append({
                "name": f"Sample {i + 1}",
                "rmsd_complex": s_rmsd["rmsd_complex"],
                "lrmsd": s_rmsd["lrmsd"],
                "contact_f1": s_contact_met["f1"],
            })
            sample_rmsds.append(s_rmsd["rmsd_complex"])

        # Sort by RMSD
        samples_data.sort(key=lambda x: x["rmsd_complex"])

        # Plot sample distribution
        best_idx = sample_rmsds.index(min(sample_rmsds))
        plot_metric_distribution(
            sample_rmsds, "Complex RMSD", "Å",
            plots_dir / "sample_rmsd_distribution.png",
            highlight_idx=best_idx
        )
        plt.close()

    # Render HTML report
    if HAS_JINJA2:
        template = Template(REPORT_TEMPLATE)
        html = template.render(
            sample_id=sample_id,
            rmsd=rmsd_metrics,
            contacts=contact_met,
            samples=samples_data,
        )
    else:
        # Simple fallback without jinja2
        html = _render_simple_report(sample_id, rmsd_metrics, contact_met, samples_data)

    report_path = out_dir / "report.html"
    with open(report_path, "w") as f:
        f.write(html)

    return str(report_path)


def _render_simple_report(sample_id, rmsd, contacts, samples):
    """Fallback report rendering without jinja2."""
    samples_html = ""
    if samples:
        rows = "\n".join(
            f"<tr><td>{i+1}</td><td>{s['name']}</td><td>{s['rmsd_complex']:.2f}</td>"
            f"<td>{s['lrmsd']:.2f}</td><td>{s['contact_f1']:.2f}</td></tr>"
            for i, s in enumerate(samples)
        )
        samples_html = f"""
        <div class="section">
            <h2>Sample Ranking</h2>
            <table>
                <tr><th>Rank</th><th>Sample</th><th>RMSD</th><th>LRMSD</th><th>F1</th></tr>
                {rows}
            </table>
        </div>
        """

    return f"""
    <!DOCTYPE html>
    <html>
    <head><title>TinyFold Report: {sample_id}</title></head>
    <body>
        <h1>{sample_id}</h1>
        <h2>RMSD Metrics</h2>
        <p>Complex: {rmsd['rmsd_complex']:.2f} Å, LRMSD: {rmsd['lrmsd']:.2f} Å</p>
        <h2>Contacts</h2>
        <p>Precision: {contacts['precision']:.2f}, Recall: {contacts['recall']:.2f}, F1: {contacts['f1']:.2f}</p>
        <h2>Viewer</h2>
        <iframe src="viewer.html" width="100%" height="600"></iframe>
        {samples_html}
    </body>
    </html>
    """
